version: '3.5'
services:
    web:
      container_name: todos
      build: .
      volumes:
        - './:/app' 
      ports: 
        - '4200:4200'
      command: > 
        bash -c "npm install && ng serve --host 0.0.0.0 --disableHostCheck true --port 4200"