version: '3.5'
services:
    web:
      container_name: todos
      build: .
      volumes:
        - './:/app' 
      ports: 
        - '4200:4200'
      command: > 
        bash -c "ng serve --host todos.social --disableHostCheck true --port 4200"